context:
  version: "0.22.0"

package:
  name: upterm
  version: ${{ version }}

source:
  url: https://github.com/owenthereal/upterm/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 047bcb184cc5189ea5f155d6a62780206fb01f093672e7b4c887cb7aa50bcc7f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - upterm version
      - upterm --help
      - uptermd version
      - uptermd --help

about:
  homepage: https://github.com/owenthereal/upterm
  repository: https://github.com/owenthereal/upterm
  documentation: https://upterm.dev/
  summary: Secure terminal sharing for remote pair programming and debugging
  description: |
    Upterm is an open-source tool enabling developers to share terminal sessions
    securely over the web. It is designed for remote pair programming, accessing
    systems behind firewalls, and remote debugging. Written in Go, it compiles
    into a single binary with no runtime dependencies.
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/

extra:
  recipe-maintainers:
    - claydugo
