context:
  version: "0.36.0"

package:
  name: upterm
  version: ${{ version }}

source:
  url: https://github.com/owenthereal/upterm/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0c9cff5d45d2781f5bc95fb783befb92e75a017b70a221a6bc6853f738e99b01

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - upterm version
      - upterm --help
      - uptermd version
      - uptermd --help

about:
  homepage: https://github.com/owenthereal/upterm
  repository: https://github.com/owenthereal/upterm
  documentation: https://upterm.dev/
  summary: Secure terminal sharing for remote pair programming and debugging
  description: |
    Upterm is an open-source tool enabling developers to share terminal sessions
    securely over the web. It is designed for remote pair programming, accessing
    systems behind firewalls, and remote debugging. Written in Go, it compiles
    into a single binary with no runtime dependencies.
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/

extra:
  recipe-maintainers:
    - claydugo
